### ISSUE TITLE
Altitude Trigger

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#10]
We need a backup function in case our command doens't go through to the Deployment Module that's capable of triggering the deployment of the payload. This is a purely software task where we need to handle the logic of once we have the altitude as a floating point number how can we interpret it to deploy. You may use an array with floats to simulate the sensor readings.
**Beware** our sensor readings are not currently very accurate, therefore we might need a solution that doesn't depend on an exact number but rather comparing to a certain reference. For instace a viable option is once a maximum altitude is recognized, we only trigger once we are below 400 ft of that maximum altitude.

Tasks:
- [ ] Make a function that accepts a floating point number and returns a boolean determinig if we should trigger or not
- [ ] Test it using a set of dummy floating point numbers in an array

**Comment by CodingIndeed** [comment]
Done, the resolved file can be found deploy_module/deploy_module_backup

**Comment by CodingIndeed** [comment]
Done, the resolved file can be found deploy_module/deploy_module_backup
