### ISSUE TITLE
DC Motor Class :: Velocity Feature

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#100]
Modify the code in the DC Motor Class created in #99 so that we can control the speed and direction of the DC motor.

### Tasks
- [x] Add an `int` input parameter to the `MOVE` function in the DC motor class (both in header and implementation file)
> Input should be between `-100` and `100`
- [x] Use the input to change the time delay of both HighDelay and LowDelay
> From tests it seems that `HighDelay=50` and `LowDelay=50` is the slowest yet most stable configuration and something like `HighDelay=500` and `LowDelay=1` is the fastest configuration. Note these *delays* are in **milliseconds**.

## Blocked by
- [x] #99

**Comment by CodingIndeed** [comment]
Done, the completed file is under "testing_dev/dc-motor-test".
