### ISSUE TITLE
BAROMETER Backend Class

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#104]
Inside `SOAR_Echo_Base/Models/barometer.py` there is an empty class labeled *Barometer* we will use this class to basically hold any data that may come from a *Barometer* sensor on our rocket, therefore we need to add some properties from the [Adafruit BMP390](https://learn.adafruit.com/adafruit-bmp388-bmp390-bmp3xx/arduino).

- [x] Add properties to the `imu` class to hold all the data that may come from an IMU sensor
- [x] Some properties might sometimes not come through so make it optional to use all of the imu properties

## Guided solution
Feel free to follow this solution or create your own
1. Look into all the properties the [Adafruit BMP390](https://learn.adafruit.com/adafruit-bmp388-bmp390-bmp3xx/arduino) can output and their most likely data types, like `altitude` could be a single float.
2. Include as much of the BMP parameters in the data class constructor. So basically include them both in the constructor's paramters and below the constructor. Example:
```
def __init__(self, altitude):
    self.altitude = altitude
```
3. Make sure the parameters on the constructor are by default `None` so it's not required to add all of them when instantiating an object of type `Altitude`

**Comment by CodingIndeed** [comment]
Done, the file can be found under "SOAR_Echo_Base/Models"
