### ISSUE TITLE
GPS Class :: Setup function

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#114]
Create a setup function for the GPS  class that encapsulates the funcitonality in the following lines:
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/e2b0aff41c108da5ff90158f7c9cc72d48e2c5ff/slave_module_rocket/slave_module_rocket.ino#L52-L64

## Guided solution
1. Create some class properties for these 2 variables:
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/e2b0aff41c108da5ff90158f7c9cc72d48e2c5ff/slave_module_rocket/slave_module_rocket.ino#L12-L13
4. Define the function in SOAR_GPS.h like this in the public section:
```c++
void setup();
```
3. Define the function i the SOAR_GPS.cpp like this:
```c++
void SOAR::setup(){
...
}
```
4. Includ ethe funciontionality from [here ](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/e2b0aff41c108da5ff90158f7c9cc72d48e2c5ff/slave_module_rocket/slave_module_rocket.ino#L52-L64) in the `setup` function

**Comment by stephanielue8088** [comment]
**This is my attempt for the header file and has been committed in VSC**


```#ifdef SOAR_GPS_H // Check if macro was previously defined 
#define SOAR_GPS_H // if macro is has not been defined, then define it


// Instruct 1: Create some class properties for these 2 variables
                // HardwareSerial GPSSerial(1); 
                // Adafruit_GPS GPS(&GPSSerial); 


#include <HardwareSerial.h> //define classes and functions related to hardware serial communication.
#include <Adafruit_GPS.h> // access the functionality provided by Adafruit GPS libraries.


class SOAR_GPS{
    public:
        SOAR_GPS(uint8_t RX, uint8_t TX); //initialize constructor to accept 8-bit paramaters, rxPin and txPin

        //Instruct2 : Define the function in SOAR_GPS.h like this in the public section:
        void setup()

    private:
    HardwareSerial GPSSerial; // Class and object
    Adafruit_GPS GPS; // Class and object

};

#endif

/
```

**This is my attempt at the setup function and has been committed in VSC**
```

#include "SOAR_GPS.h"

SOAR_GPS::SOAR_GPS(uint8_t rxPin, uint8_t txPin):GPSSerial(1),GPS(&GPSSerial)

{
    GPSSerial.begin(9600, SERIAL_8N1, RX, TX);
    
}
   

void SOAR_GPS::setup();
 {
    GPS.begin(9600);

    GPS.sendCommand(PMTK_SET_NMEA_OUTPUT_RMCONLY);

    GPS.sendCommand(PMTK_SET_NMEA_UPDATE_1HZ);   // 1 Hz update rate

    GPS.sendCommand(PGCMD_ANTENNA);
     // delay(1000);
    // Ask for firmware version
    GPSSerial.println(PMTK_Q_RELEASE);
  
    Serial.println("Setup completed");

    Serial.print("GPS Sensor Object created");
}
```
