### ISSUE TITLE
Add a Piezo to Deploy module

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#12]
Add a piezo to stepper module and hook it up to some pins on the ESP32S3

Tasks:
- [ ] Solder a a Piezo to the microcontroller of the Deploy Module
- [ ] Modify the code in deploy_module if already exists. If not write a comment with the Pin number

**Comment by L42ARO** [comment]
Cannot find piezo

**Comment by Pavan-da-Coder** [comment]
Pins soldered on GPIO1 for ESP32 Mini
