### ISSUE TITLE
Shorten Down GPS Data

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#16]
In the slave_module we have the following code sending the GPS data:
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/cfbe566289dd5dce432a38b0feed17785f4a46ad/slave_module/slave_module.ino#L88-L91

The data looks something like this:
`$GNRMC,014854.000,A,2803.9643,N,08225.0154,W,0.30,205.59,121223,,,A*6B`
Figure out a way to reduce the string we are sending to just the crucial GPS data

Tasks: 
- [ ] Modify the code in [slave_module](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/main/slave_module/) so that the gps_data_string has less chars
- [ ] It can be tested by writing your own Arduino program put `$GNRMC,014854.000,A,2803.9643,N,08225.0154,W,0.30,205.59,121223,,,A*6B` into a string variable and see if your logic extracts the needed data

**Comment by Pavan-da-Coder** [comment]
Completed, see commit titled "Modify slave_module to shorten GPS data".
