### ISSUE TITLE
CSV log for arduino serial

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#28]
If the serial functionality to get stuff from the Arduino serial is working, add the functionality to store that data in a csv file. Each time the program boots up it should create a csv file that has for name the current date time, and the serial data itself should be logged with the datetime it came in. So the csv should in essence just have 2 columns `datetime` and `serial msg`
```
datetime, serial msg
12-14-2023 15:15:20, gps: some gps data
12-14-2023 15:17:25, acknoledge: deploy
12-14-2023 15:20:40, acknoledge: landing
```

Tasks:
- [ ] Modify code in [lora.py](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/main/SOAR_Echo_Base/Services/lora.py) to log the serial data into a csv

**NOTE:** If need guidance look into how we log sensor data in our raspberry pi [here](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/main/zero_dev/mods/sensors.py)

**Comment by CodingIndeed** [comment]
The file is called New_lora.py and is located under the Services in SOAR_Echo_Base
