### ISSUE TITLE
Update stepper motor code

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#41]
We have switched our stepper motor to a Nema 23 stepper motor, requiring a different motor driver, the following code was working with the motor driver, so we need to make sure our old code works like this one:
```
// Define stepper motor connections:
#define dirPin 2
#define stepPin 3

void setup() {
  // Declare pins as output:
  pinMode(stepPin, OUTPUT);
  pinMode(dirPin, OUTPUT);

  // Set the spinning direction CW/CCW:
  digitalWrite(dirPin, LOW);
}
uint32_t cycles = 0;
void loop() {
  cycles++;
  if (cycles>=5000 && cycles <5100){
    digitalWrite(dirPin, HIGH);
  }
  if(cycles>=5100){
    digitalWrite(dirPin, LOW);
    cycles=0;
  }
  // These four lines result in 1 step:
  digitalWrite(stepPin, HIGH);
  delayMicroseconds(600);
  digitalWrite(stepPin, LOW);
  delayMicroseconds(600);
}
```
Here is the tutorial we followed to get the motor working: [tutorial](https://www.makerguides.com/tb6600-stepper-motor-driver-arduino-tutorial/)

Update this piece of the code:
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/19428ee7ee069c5c42cd726646ae68ebfcfa1ea9/deploy_module/deploy_module_backup/deploy_module_backup.ino#L73

**Comment by CodingIndeed** [comment]
Done, the file can be found under deploy_module_backup.
