### ISSUE TITLE
🧐 Get the current deployment status from the Deployment class

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#56]
`EXTENDING` if we're on the extending phase
`WAITING` if we're waiting for the drone to drop
`RETRACTING` if we're on the retracting phase
`PAUSED` if it's not active but at least another state is true
`IDLE` if all the states are false 
`COMPLETED` if all the states are completed

- [x] Add a method to get the current deployment status from the `Deployment` class

## Guided solution
1. Add a function on the [public section of the Deployment class](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/4da67264c5ddeb4b785fdbd42b13153f51d7bf1b/deploy_module/deploy_module_backup/deploy_module_backup.ino#L195), call it like this:
```c++
String GetStatus(){}
```
2. In said function use [the private variables of the Deployment class](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/4da67264c5ddeb4b785fdbd42b13153f51d7bf1b/deploy_module/deploy_module_backup/deploy_module_backup.ino#L267-L276) to return a string indicative of the state, use the following chart as a guide:
```mermaid
flowchart LR
a[NOT _active] --> IDLE
z[NOT _active but either _forward, _nimble or _retract are TRUE] --> PAUSED
b[_active but NOT _forward] --> EXTENDING
c[_active and _forward and NOT _nimble] --> WAITING
d[_active and _forward and _nimble but NOT _retract] --> RETRACTING
e[_forward and _nimble and _retract] --> COMPLETED
```
3. Make sure to return the status and that the type of the return is a `String`

**Comment by Omar-Khalaf22** [comment]
Comitted changes.
