### ISSUE TITLE
🧑‍🚀 Submit order for the STEMNauts

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#62]
We have selected our specific options for STEMnaut sensors, so we need to submit the order to purchase them ASAP. So add the following items to the SOAR purchasing sheet:
- [x] Adafruit BNO055 (x5)
- [x] Adafruit BMP390 (x5)
- [x] Adafruit I2S Microphone (x5)

> **IF** you have access to the purchasing sheet directly put them there
> **ELSE** use this [google sheets on page 3](https://docs.google.com/spreadsheets/d/1VBxpbiQMJ-oRr6qzQrn8Js6XJOccSIo2IFfPeHvK6Ts/edit#gid=1439637238)
> **NOTE**: If item if from `Amazon` there's no need for shippping

**Comment by esmeraldagarcia1** [comment]
Amazon Astronauts:
https://www.amazon.com/LEGO-City-Space-Port-Astronaut/dp/B09Q1J5JW5/ref=sr_1_6?keywords=lego+astronaut+minifigure&qid=1706136870&sr=8-6

https://www.amazon.com/LEGO-City-MiniFigure-Space-Astronaut/dp/B01MS7XMY5/ref=sr_1_3?keywords=lego+astronaut+minifigure&qid=1706136870&sr=8-3

Mercari Legos 4 pack: 
https://www.mercari.com/us/item/m93103790830/?gclsrc=aw.ds&&utm_source=google&utm_medium=cpc&utm_campaign=18346788881&utm_content=t0&adgroup=141326147677&network=g&device=c&merchant_id=126358573&product_id=m93103790830&product_id=1993143902837&gad_source=4&gclid=Cj0KCQiAh8OtBhCQARIsAIkWb6_usWf_A__M7Rw6HIlUckDrT1GL6A-tSpjZMWsa-5uSSwqTExW4RFQaAsvgEALw_wcB

Green Spaceman:
https://www.bonanza.com/listings/Spaceman-Chrome-Green-Astronaut-Lego-Compatible-Minifigure-Bricks-Toys/1390999506?goog_pla=1
