### ISSUE TITLE
Connect Adafruit 900Mhz Transciever and Test it

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#69]
Use a breadboard and jumper wires for the following:
- [ ] Connect the Adafruit RF Module module to the ESP32S3
- [ ] Connect the Adafruit RF module to an Arduino
- [ ] Transmit data from one end to the other
- [ ] Document on the wiki how you got it to work

**Comment by Pavan-da-Coder** [comment]
To connect with an Arduino Uno to an Arduino Uno,
Follow the wiring diagram EXACTLY as is shown
https://www.airspayce.com/mikem/arduino/RadioHead/classRH__RF95.html
![image](https://github.com/usfsoar/NSL_23-24_PayloadEECS/assets/61098154/7c3e9e77-255a-41c9-a2fc-89af5bbf5c78)

**Comment by Pavan-da-Coder** [comment]
Next task is to solder pins and connect the transceiver to the ESP32-S3

**Comment by Pavan-da-Coder** [comment]
Sample Code, condensed, from community
https://forums.adafruit.com/viewtopic.php?t=104190

Sample code, not condensed, from developers
https://www.airspayce.com/mikem/arduino/RadioHead/rf95_reliable_datagram_client_8pde-example.html
https://www.airspayce.com/mikem/arduino/RadioHead/rf95_reliable_datagram_server_8pde-example.html

Documentation:
https://www.airspayce.com/mikem/arduino/RadioHead/classRH__RF95.html#a274c170acdb53f55fd45445ab7f51889

**Comment by Pavan-da-Coder** [comment]
Documentation parent links:
https://www.airspayce.com/mikem/arduino/RadioHead/
https://www.airspayce.com/mikem/arduino/RadioHead/examples.html
