### ISSUE TITLE
Parsing Logic for SENSORS :: If else endpoints

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#94]
Create a bunch of if else statements for parsing the data we receive form the sensors in the python backend in [this file](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/main/SOAR_Echo_Base/Services/parser.py) for the following:
- `ALTITUDE` (note replace the one that says `ALTI` for this one)
- `IMU`
- `BAROMETER`
- `DECIBEL`

For now just log the messages, we are still pending to create APIs to relay them to the UI.

## Guided solution
- Look at the *if* and *else* statements in these lines and see how they check if a certain word is in the incoming `message` varaiable
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/8e5094ac1895bd41e44e6c06290fc23d55297595/SOAR_Echo_Base/Services/parser.py#L11-L27
- Do the same for the words above, and inside the if else statements just print the type of message like:
```python
print("Received altitude message);
```
- Finally call control_panel.log_msg(message) inside of the statements

**Comment by CodingIndeed** [comment]
The edited version is located on the NSL_23-24_PayloadEECS/SOAR_Echo_Base/Services. The file is called "New_Parser.py".
